"""Add_pipeline_refactor_fields

Revision ID: 20cb990a3f94
Revises: cfaf53a3bd44
Create Date: 2026-07-13 22:04:39.076661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20cb990a3f94'
down_revision: Union[str, None] = 'cfaf53a3bd44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_documents', sa.Column('validation_report', sa.JSON(), nullable=True))
    op.add_column('risk_aggregates', sa.Column('evidence_coverage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_aggregates', 'evidence_coverage')
    op.drop_column('claim_documents', 'validation_report')
    # ### end Alembic commands ###
